//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать фото.
    /// </summary>
    // *** Start programmer edit section *** (ПечатьФото CustomAttributes)

    // *** End programmer edit section *** (ПечатьФото CustomAttributes)
    [AutoAltered()]
    [Caption("Печать фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьФотоE", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "Носитель as \'Носитель\'",
            "ВидФото as \'Фото\'",
            "Количество as \'Количество\'"})]
    [AssociatedDetailViewAttribute("ПечатьФотоE", "Коррекция", "КоррекцияE", true, "", "Коррекция", true, new string[] {
            ""})]
    [View("ПечатьФотоL", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "Носитель as \'Носитель\'",
            "Количество as \'Количество\'",
            "ВидФото as \'Фото\'"})]
    public class ПечатьФото : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаказа;
        
        private IIS.Kursovaya9.ВидНосителя fНоситель;
        
        private IIS.Kursovaya9.ВыборВида fВидФото;
        
        private int fКоличество;
        
        private IIS.Kursovaya9.Фотокиоск fФотокиоск;
        
        private IIS.Kursovaya9.DetailArrayOfКоррекция fКоррекция;
        
        // *** Start programmer edit section *** (ПечатьФото CustomMembers)

        // *** End programmer edit section *** (ПечатьФото CustomMembers)

        
        /// <summary>
        /// ВидФото.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.ВидФото CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.ВидФото CustomAttributes)
        public virtual IIS.Kursovaya9.ВыборВида ВидФото
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.ВидФото Get start)

                // *** End programmer edit section *** (ПечатьФото.ВидФото Get start)
                IIS.Kursovaya9.ВыборВида result = this.fВидФото;
                // *** Start programmer edit section *** (ПечатьФото.ВидФото Get end)

                // *** End programmer edit section *** (ПечатьФото.ВидФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.ВидФото Set start)

                // *** End programmer edit section *** (ПечатьФото.ВидФото Set start)
                this.fВидФото = value;
                // *** Start programmer edit section *** (ПечатьФото.ВидФото Set end)

                // *** End programmer edit section *** (ПечатьФото.ВидФото Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Количество CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Количество Get start)

                // *** End programmer edit section *** (ПечатьФото.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ПечатьФото.Количество Get end)

                // *** End programmer edit section *** (ПечатьФото.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Количество Set start)

                // *** End programmer edit section *** (ПечатьФото.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ПечатьФото.Количество Set end)

                // *** End programmer edit section *** (ПечатьФото.Количество Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.НомерЗаказа Get start)

                // *** End programmer edit section *** (ПечатьФото.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (ПечатьФото.НомерЗаказа Get end)

                // *** End programmer edit section *** (ПечатьФото.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.НомерЗаказа Set start)

                // *** End programmer edit section *** (ПечатьФото.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (ПечатьФото.НомерЗаказа Set end)

                // *** End programmer edit section *** (ПечатьФото.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Носитель.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Носитель CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Носитель CustomAttributes)
        public virtual IIS.Kursovaya9.ВидНосителя Носитель
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Носитель Get start)

                // *** End programmer edit section *** (ПечатьФото.Носитель Get start)
                IIS.Kursovaya9.ВидНосителя result = this.fНоситель;
                // *** Start programmer edit section *** (ПечатьФото.Носитель Get end)

                // *** End programmer edit section *** (ПечатьФото.Носитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Носитель Set start)

                // *** End programmer edit section *** (ПечатьФото.Носитель Set start)
                this.fНоситель = value;
                // *** Start programmer edit section *** (ПечатьФото.Носитель Set end)

                // *** End programmer edit section *** (ПечатьФото.Носитель Set end)
            }
        }
        
        /// <summary>
        /// Печать фото.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Фотокиоск CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Фотокиоск CustomAttributes)
        [PropertyStorage(new string[] {
                "Фотокиоск"})]
        [NotNull()]
        public virtual IIS.Kursovaya9.Фотокиоск Фотокиоск
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Фотокиоск Get start)

                // *** End programmer edit section *** (ПечатьФото.Фотокиоск Get start)
                IIS.Kursovaya9.Фотокиоск result = this.fФотокиоск;
                // *** Start programmer edit section *** (ПечатьФото.Фотокиоск Get end)

                // *** End programmer edit section *** (ПечатьФото.Фотокиоск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Фотокиоск Set start)

                // *** End programmer edit section *** (ПечатьФото.Фотокиоск Set start)
                this.fФотокиоск = value;
                // *** Start programmer edit section *** (ПечатьФото.Фотокиоск Set end)

                // *** End programmer edit section *** (ПечатьФото.Фотокиоск Set end)
            }
        }
        
        /// <summary>
        /// Печать фото.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Коррекция CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Коррекция CustomAttributes)
        public virtual IIS.Kursovaya9.DetailArrayOfКоррекция Коррекция
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Коррекция Get start)

                // *** End programmer edit section *** (ПечатьФото.Коррекция Get start)
                if ((this.fКоррекция == null))
                {
                    this.fКоррекция = new IIS.Kursovaya9.DetailArrayOfКоррекция(this);
                }
                IIS.Kursovaya9.DetailArrayOfКоррекция result = this.fКоррекция;
                // *** Start programmer edit section *** (ПечатьФото.Коррекция Get end)

                // *** End programmer edit section *** (ПечатьФото.Коррекция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Коррекция Set start)

                // *** End programmer edit section *** (ПечатьФото.Коррекция Set start)
                this.fКоррекция = value;
                // *** Start programmer edit section *** (ПечатьФото.Коррекция Set end)

                // *** End programmer edit section *** (ПечатьФото.Коррекция Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоE", typeof(IIS.Kursovaya9.ПечатьФото));
                }
            }
            
            /// <summary>
            /// "ПечатьФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоL", typeof(IIS.Kursovaya9.ПечатьФото));
                }
            }
        }
    }
}
